export default {
    ROLE: ['ADMIN', 'USER'],
    USER_STATUS: ['ACTIVE', 'INACTIVE'],
    SUBSCRIPTION: ['FREE', 'PAID'],
    MFA: ['EMAIL', 'PHONE', 'AUTHENTICATOR'],
    REPORT_STATUS: ['PENDING', 'RESOLVED', 'BLOCKED', 'WARNED'],
    MEDIA_TYPE: ['VIDEO', 'ARTICLE', 'WEBINAR', 'INTERVIEW'],
    CMS_PAGE_STATUS: ['DRAFT', 'PUBLISHED', 'UNPUBLISHED'],
    CONTACT_US_STATUS: ['OPEN', 'RESOLVED'],
  }
  